services:
  casanova:
    image: ghcr.io/pedrovian9/listaevento:latest
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/data
    expose:
      - "8000"
    networks:
      - edge
    restart: unless-stopped

networks:
  edge:
    external: true