import { expect, test } from '@playwright/test'

test('administração, convite, presença, presentes e regeneração de link', async ({ page }, testInfo) => {
  const suffix = `${testInfo.project.name}-${Date.now()}`
  const guestName = `Convidado ${suffix}`
  const giftName = `Jogo de toalhas ${suffix}`
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('https://example.com/**', route => route.abort())
  await page.goto('/admin')
  await expect(page).toHaveURL(/\/admin\/login/)
  await page.getByLabel(/^Usuário/).fill('browser-test')
  await page.getByLabel(/^Senha/).fill('senha-incorreta')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByText('Usuário ou senha incorretos.')).toBeVisible()
  await page.getByLabel(/^Senha/).fill('browser-test-only-password')
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Visão geral' })).toBeVisible()

  await page.goto('/admin/configuracoes')
  await page.getByLabel('Nome do casal').fill('Pedro & Maria')
  await page.getByLabel('Data', { exact: true }).fill('2026-10-18')
  await page.getByLabel('Hora', { exact: true }).fill('16:00')
  await page.getByLabel('Endereço', { exact: true }).fill('Jardim do Encontro, 123')
  await page.getByLabel('URL do Google Maps').fill('https://maps.google.com/?q=Jardim')
  await page.getByRole('switch', { name: 'Permitir acompanhantes' }).check()
  await page.getByRole('button', { name: 'Salvar configurações' }).click()
  await expect(page.getByText('Detalhes do evento atualizados!')).toBeVisible()

  await page.goto('/admin/convidados')
  await page.getByRole('button', { name: 'Novo convidado', exact: true }).click()
  await page.getByRole('dialog').getByLabel(/^Nome/).fill(guestName)
  await page.getByLabel('Observação (opcional)').fill('Observação confidencial do casal')
  await page.getByRole('button', { name: 'Salvar convidado' }).click()
  const invitationLink = await page.getByLabel('Link do convite').inputValue()
  expect(invitationLink).toContain('/convite/')
  await page.getByRole('button', { name: 'Fechar', exact: true }).click()
  await expect(page.getByText(guestName, { exact: true })).toBeVisible()

  await page.goto('/admin/presentes')
  await page.getByRole('button', { name: 'Novo presente', exact: true }).click()
  await page.getByRole('dialog').getByLabel(/^Nome/).fill(giftName)
  await page.getByLabel('Descrição', { exact: true }).fill('Jogo com quatro peças para a nossa casa.')
  await page.getByLabel(/^URL da imagem/).fill('https://example.com/indisponivel.jpg')
  await page.getByLabel('URL da sugestão de compra').fill('https://example.com/produto')
  await page.getByLabel('Quantidade desejada').fill('2')
  await page.getByRole('button', { name: 'Salvar presente' }).click()
  await expect(page.getByRole('heading', { name: giftName, exact: true })).toBeVisible()

  await page.goto(invitationLink)
  await expect(page.getByRole('heading', { name: `Olá, ${guestName}!`, exact: true })).toBeVisible()
  await expect(page.getByText('Observação confidencial do casal')).toHaveCount(0)
  await page.getByRole('button', { name: 'Confirmar presença', exact: true }).first().click()
  await page.getByRole('button', { name: 'Aumentar quantas pessoas irão com você?' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirmar presença', exact: true }).click()
  await expect(page.getByText('Presença confirmada! Estamos esperando você 💙', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Presença confirmada! Estamos esperando você 💙', { exact: true })).toBeVisible()
  await page.getByLabel('Buscar presente', { exact: true }).fill(giftName)
  const card = page.locator('.MuiCard-root').filter({ has: page.getByRole('heading', { name: giftName, exact: true }) })
  await expect(card.getByText('Imagem indisponível')).toBeVisible()
  await expect(card.getByRole('link', { name: 'Ver sugestão' })).toHaveAttribute('target', '_blank')
  await expect(card.getByRole('link', { name: 'Ver sugestão' })).toHaveAttribute('rel', 'noopener noreferrer')
  await page.screenshot({ path: testInfo.outputPath('convite.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await card.getByRole('button', { name: 'Comprei esse ou similar' }).click()
  await page.getByRole('button', { name: 'Confirmar compra' }).click()
  await expect(card.getByText('1 de 2 comprados')).toBeVisible()
  await card.getByRole('button', { name: 'Comprei esse ou similar' }).click()
  await page.getByRole('button', { name: 'Confirmar compra' }).click()
  await expect(card.getByRole('button', { name: 'Completo ✓' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Salvar minha confirmação' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Alterar resposta' }).click()
  await page.getByRole('button', { name: 'Não poderei ir' }).click()
  await expect(page.getByText('Você informou que não poderá ir. Sentiremos sua falta!')).toBeVisible()

  await page.goto('/admin/convidados')
  await page.getByLabel('Buscar convidado').fill(guestName)
  await expect(page.getByText('Não irá', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('admin-convidados.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: `Mais ações para ${guestName}` }).click()
  await page.getByRole('menuitem', { name: 'Regenerar link' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Regenerar link' }).click()
  const renewed = await page.getByLabel('Link do convite').inputValue()
  expect(renewed).not.toBe(invitationLink)
  await page.goto(invitationLink)
  await expect(page.getByText('Este convite não foi encontrado. Peça um novo link ao casal.')).toBeVisible()
  await page.goto(renewed)
  await expect(page.getByRole('heading', { name: `Olá, ${guestName}!` })).toBeVisible()
  await page.goto('/admin')
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: 'Abrir menu' }).click()
  await page.getByRole('button', { name: 'Sair da conta' }).click()
  await expect(page).toHaveURL(/\/admin\/login/)
  expect(errors).toEqual([])
})

test('um convite familiar usa o nome no link e na saudação e confirma somente as pessoas marcadas', async ({ page }, testInfo) => {
  await page.request.post('/api/admin/auth/login', { data: { username: 'browser-test', password: 'browser-test-only-password' } })
  await page.goto('/admin/convidados')
  await page.getByRole('button', { name: 'Novo convidado', exact: true }).click()
  await page.getByRole('dialog').getByLabel(/^Nome/).fill('Madrinha e família')
  await page.getByRole('button', { name: 'Adicionar família' }).click()
  const names = ['Cláudia', 'Carlos', 'Ana', 'João', 'Lúcia', 'Luís', 'Beatriz']
  for (let i = 0; i < names.length; i++) {
    if (i > 1) await page.getByRole('button', { name: 'Adicionar pessoa', exact: true }).click()
    await page.getByLabel(new RegExp(`^Pessoa ${i + 1}`)).fill(names[i])
  }
  await page.getByRole('button', { name: 'Salvar convidado' }).click()
  const link = await page.getByLabel('Link do convite').inputValue()
  expect(new URL(link).pathname).toMatch(/^\/convite\/madrinha-e-familia(?:-\d+)?$/)
  await page.goto(link)
  await expect(page.getByRole('heading', { name: 'Olá, Madrinha e família!', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Confirmar presença', exact: true }).first().click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('checkbox')).toHaveCount(7)
  await expect(dialog.getByRole('button', { name: 'Confirmar presença', exact: true })).toBeDisabled()
  for (const name of ['Carlos', 'Ana', 'João', 'Lúcia']) await dialog.getByRole('checkbox', { name, exact: true }).check()
  await dialog.screenshot({ path: testInfo.outputPath('familia-selecao.png') })
  await dialog.getByRole('button', { name: 'Confirmar presença', exact: true }).click()
  await expect(page.getByText('4 pessoa(s) confirmada(s)', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Salvar minha confirmação' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Confirmar presença', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.getByText('4 pessoa(s) confirmada(s)', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Alterar resposta' }).click()
  await expect(dialog.getByRole('checkbox', { name: 'Cláudia', exact: true })).not.toBeChecked()
  await expect(dialog.getByRole('checkbox', { name: 'Carlos', exact: true })).toBeChecked()
  await dialog.getByRole('checkbox', { name: 'Cláudia', exact: true }).check()
  await dialog.getByRole('checkbox', { name: 'Carlos', exact: true }).uncheck()
  await dialog.getByRole('button', { name: 'Confirmar presença', exact: true }).click()
  const response = await page.request.get(`/api/convites/${new URL(link).pathname.split('/').pop()}`)
  const invitation = await response.json()
  expect(invitation.membros.filter((m: { status_presenca: string }) => m.status_presenca === 'CONFIRMADO').map((m: { nome: string }) => m.nome)).toEqual(['Cláudia', 'Ana', 'João', 'Lúcia'])
  await page.goto('/admin/convidados')
  await page.getByLabel('Buscar convidado').fill('Madrinha e família')
  await expect(page.getByText('4 de 7 pessoas confirmadas').first()).toBeVisible()
})

test('página inicial não revela convidados nem presentes sem token', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Pedro & Maria', level: 1 })).toBeVisible()
  await expect(page.getByText('Recebeu nosso convite?', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Comprei esse ou similar' })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
