import { expect, test } from '@playwright/test'

test('converter Pix, copiar chave e calcular estimativa dos produtos', async ({ page, context }, testInfo) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.request.post('/api/admin/auth/login', { data: { username: 'browser-test', password: 'browser-test-only-password' } })
  const before = await (await page.request.get('/api/admin/dashboard')).json()
  const name = `Contribua com Pix ${testInfo.project.name}`
  const legacy = await (await page.request.post('/api/admin/presentes', { data: { nome: name, imagem_url: 'https://example.com/pix.png', valor: '9999.00', quantidade_desejada: 999 } })).json()
  await page.route('https://example.com/**', route => route.fulfill({ path: 'public/ladrilho.png', contentType: 'image/png' }))
  await page.goto('/admin/presentes')
  const card = page.locator(`[data-gift-id="${legacy.id}"]`)
  await card.getByRole('button', { name: 'Editar', exact: true }).click()
  await page.getByLabel('Tipo de item').click()
  await page.getByRole('option', { name: 'Contribuição Pix' }).click()
  await page.getByLabel(/^Chave Pix/).fill('casal@example.com')
  await page.getByLabel('Banco do Pix').click()
  await page.getByRole('option', { name: 'Itaú', exact: true }).click()
  await page.getByLabel(/^URL da imagem/).fill('https://example.com/pix-photo.png')
  await expect(page.getByLabel('Quantidade desejada')).toHaveCount(0)
  await expect(page.getByLabel('Valor sugerido (opcional)')).toHaveCount(0)
  await page.getByRole('button', { name: 'Salvar presente' }).click()
  await expect(card.getByText('Qualquer valor é bem-vindo 💙')).toBeVisible()
  await expect(card.getByRole('progressbar')).toHaveCount(0)
  await expect(card.getByText('casal@example.com', { exact: true })).toHaveCount(0)
  await expect(card.getByRole('img', { name: 'Logo Itaú' })).toBeVisible()
  await expect(card.getByRole('img', { name, exact: true })).toBeVisible()
  await page.reload()
  await expect(card.getByRole('img', { name: 'Logo Itaú' })).toBeVisible()
  await card.getByRole('button', { name: 'Copiar chave Pix' }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('casal@example.com')
  const after = await (await page.request.get('/api/admin/dashboard')).json()
  expect(after).toEqual(before)
  const guest = await (await page.request.post('/api/admin/convidados', { data: { nome: name } })).json()
  const product = await (await page.request.post('/api/admin/presentes', { data: { nome: `Produto ${name}`, imagem_url: 'https://example.com/gift.png', valor: '129.90', quantidade_desejada: 2 } })).json()
  await page.request.post(`/api/convites/${guest.token}/presentes/${product.id}/comprar`, { data: { quantidade: 2 } })
  await page.goto(`/convite/${guest.token}`)
  await expect(card.getByRole('button', { name: 'Comprei esse ou similar' })).toHaveCount(0)
  await expect(card.getByRole('button', { name: 'Copiar chave Pix' })).toBeVisible()
  await expect(card.getByText('casal@example.com', { exact: true })).toHaveCount(0)
  await expect(card.getByRole('img', { name: 'Logo Itaú' })).toBeVisible()
  expect(await card.getByRole('img', { name, exact: true }).evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true)
  await card.screenshot({ path: testInfo.outputPath('pix-card.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.goto('/admin')
  const estimate = page.locator('.MuiCard-root').filter({ hasText: 'Valor estimado arrecadado' })
  const expected = Number(before.valor_estimado_arrecadado) + 259.8
  await expect(estimate.getByText(expected.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }), { exact: true })).toBeVisible()
  await estimate.screenshot({ path: testInfo.outputPath('estimate-card.png') })
})
